---
title: "p8105_homelessness_final"
author: "Blair Wigsten"
date: "11/6/2019"
output: github_document
---

# Group Members 
  Blair Wigsten bw2595
  
  Nora Zakaria niz2000
  
  Kristi Chau kpc2124
  
  Alicia Yang ay2452

  
# Tentative Title
 "Homelessness in the United States"


# Motivation 
Due to a lack of accessible mental health resources, rising cost of living with stagnant wages, and housing insecurity, homelessness is on the rise in the United States. Homelessness, whether chronic or a temporary loss of shelter, is associated with high rates of communicable disease, physical ailments, and mental decline. As a group consisting of California and New York residents, homelessness as a public health issue is at the forefront. The purpose of this project is the examine the homelessness epidemic in the United States, and explore potential predictors and covariate associations.


# Intended Final Products 
  - A comprehensive website detailing the issue, key findings, and visual displays such as maps, graphs, and reports. 
  - A screencast explaining our website, how to use it, and its multiple functionalities.
  - A dashboard specifically looking at CA and NY homelessness predictors and associations, as these states experienced the highest prevalence of homelessness in 2018.
 
  
# Anticipated Data Sources
 - HUD Exchange
 - NOAA weather data


# Planned Analyses / Visualizations / Coding Challenges
### Analyses
 - We plan to analyze the differences in homelessness rates over time and 2018 point-in-time counts within States in the United States. 
 - We will also specifically analyze major contributing states (CA and NY) and whether their high prevalence is related to predictors such as weather and climate data.
  - Our exploratory analysis will also include CoC (Continuum of Care Program) state-specific data as provided in the dataset, to determine any predictors/associations.
  
### Visualizations
 - We plan to display reader-friendly interactive graphs and maps demonstrating homelessness prevalence by state/city and weather.
 - We will also utilize shinyapps to generate an interactive map to display and compare homelessness over time.

### Coding Challenges
 - Writing collaboratively, with correct collaboration pushing/pulling on Github.
 - Utilizing Shiny apps to make our interactive graphs and maps. This may pose an issue as group members are not familiar with this program.

 
# Planned Timeline
 - Group members plan to meet every Wednesday to provide updates on project progress:
 
- 11/6 – Scope of Work Planning Group Meeting: Complete Scope of Work
- 11/7 – Proposal Due
- 11/13 – Exploratory Analysis and Visualization Group Meeting: Import, Tidy, and Exploratory Analysis of Data
- 11/11 - 11/15 – Project Review Meeting 
- 11/20 – Report Writing Group Meeting: Write Report
- 11/27 – Screencast and Final Deliverable Group Meeting: Record Screencast and Update the Website
- 12/5 – Report, Webpage, and Peer Assessment Due
- 12/10 – In-Class Project Discussion
